# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_ecpf_nfe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecnpj',
            options={'ordering': ['título'], 'verbose_name_plural': 'e-CNPJ'},
        ),
        migrations.AlterModelOptions(
            name='ecpf',
            options={'ordering': ['título'], 'verbose_name_plural': 'e-CPF'},
        ),
        migrations.AlterModelOptions(
            name='nfe',
            options={'ordering': ['título'], 'verbose_name_plural': 'NF-e'},
        ),
    ]
