# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20161129_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecnpj',
            options={'ordering': ['id'], 'verbose_name_plural': 'e-CNPJ'},
        ),
        migrations.AlterModelOptions(
            name='ecpf',
            options={'ordering': ['id'], 'verbose_name_plural': 'e-CPF'},
        ),
        migrations.AlterModelOptions(
            name='nfe',
            options={'ordering': ['id'], 'verbose_name_plural': 'NF-e'},
        ),
    ]
