# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20161204_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecnpj',
            options={'ordering': ['id'], 'verbose_name_plural': 'e-CNPJ'},
        ),
    ]
