# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecnpj',
            options={'verbose_name_plural': 'e-CNPJ'},
        ),
        migrations.AlterModelOptions(
            name='ecpf',
            options={'verbose_name_plural': 'e-CPF'},
        ),
        migrations.AlterModelOptions(
            name='nfe',
            options={'verbose_name_plural': 'NF-e'},
        ),
    ]
