# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0002_auto_20161123_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecnpj',
            options={'ordering': ['posição'], 'verbose_name_plural': 'e-CNPJ'},
        ),
    ]
