# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditServiceModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=80)),
                ('descrição', models.TextField()),
                ('name_id', models.CharField(max_length=50)),
                ('serviço', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Credit Service Modal',
            },
        ),
    ]
