# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_modal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditservicemodal',
            options={'ordering': ['serviço'], 'verbose_name_plural': 'Credit Service Modal'},
        ),
    ]
